// Generated by TestForge.
package com.joydipbhakat.newsapp.data.network.models

import com.joydipbhakat.newsapp.data.local.entity.Article
import com.joydipbhakat.newsapp.data.local.entity.Source
import org.junit.Test
import org.junit.Assert.assertEquals

class ApiArticlesTest {
    
    @Test
    fun `toArticleEntity returns Article with correct values when all fields are present`() {
        // Given
        val apiSource = ApiSource("1", "BBC News")
        val apiArticles = ApiArticles(
            apiSource = apiSource,
            title = "Breaking News",
            description = "Latest updates",
            url = "https://example.com/news",
            urlToImage = "https://example.com/image.jpg"
        )
        
        // When
        val result = apiArticles.toArticleEntity()
        
        // Then
        assertEquals(Source("1", "BBC News"), result.source)
        assertEquals("Breaking News", result.title)
        assertEquals("Latest updates", result.description)
        assertEquals("https://example.com/news", result.url)
        assertEquals("https://example.com/image.jpg", result.urlToImage)
    }
    
    @Test
    fun `toArticleEntity returns Article with empty strings when fields are null`() {
        // Given
        val apiArticles = ApiArticles(
            apiSource = null,
            title = null,
            description = null,
            url = null,
            urlToImage = null
        )
        
        // When
        val result = apiArticles.toArticleEntity()
        
        // Then
        assertEquals(Source("", ""), result.source)
        assertEquals("", result.title)
        assertEquals("", result.description)
        assertEquals("", result.url)
        assertEquals("", result.urlToImage)
    }
    
    @Test
    fun `toArticleEntity returns Article with default Source when apiSource is null`() {
        // Given
        val apiArticles = ApiArticles(
            apiSource = null,
            title = "Breaking News",
            description = "Latest updates",
            url = "https://example.com/news",
            urlToImage = "https://example.com/image.jpg"
        )
        
        // When
        val result = apiArticles.toArticleEntity()
        
        // Then
        assertEquals(Source("", ""), result.source)
        assertEquals("Breaking News", result.title)
        assertEquals("Latest updates", result.description)
        assertEquals("https://example.com/news", result.url)
        assertEquals("https://example.com/image.jpg", result.urlToImage)
    }
    
    @Test
    fun `toArticleEntity returns Article with default values for missing fields`() {
        // Given
        val apiSource = ApiSource("1", "BBC News")
        val apiArticles = ApiArticles(
            apiSource = apiSource,
            title = null,
            description = null,
            url = "https://example.com/news",
            urlToImage = null
        )
        
        // When
        val result = apiArticles.toArticleEntity()
        
        // Then
        assertEquals(Source("1", "BBC News"), result.source)
        assertEquals("", result.title)
        assertEquals("", result.description)
        assertEquals("https://example.com/news", result.url)
        assertEquals("", result.urlToImage)
    }
    
    @Test
    fun `toArticleEntity handles empty string values correctly`() {
        // Given
        val apiSource = ApiSource("", "")
        val apiArticles = ApiArticles(
            apiSource = apiSource,
            title = "",
            description = "",
            url = "",
            urlToImage = ""
        )
        
        // When
        val result = apiArticles.toArticleEntity()
        
        // Then
        assertEquals(Source("", ""), result.source)
        assertEquals("", result.title)
        assertEquals("", result.description)
        assertEquals("", result.url)
        assertEquals("", result.urlToImage)
    }
}