// Generated by TestForge.
package com.joydipbhakat.newsapp.data.network.models

import com.joydipbhakat.newsapp.data.local.entity.Source
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

class ApiSourceTest {

    @Test
    fun `toSourceEntity carries both the id and the name across`() {
        val apiSource = ApiSource(id = "bbc-news", name = "BBC News")

        assertEquals(Source("bbc-news", "BBC News"), apiSource.toSourceEntity())
    }

    @Test
    fun `a null id is carried across as null rather than defaulted`() {
        val apiSource = ApiSource(id = null, name = "BBC News")

        val entity = apiSource.toSourceEntity()

        assertNull(entity.id)
        assertEquals("BBC News", entity.name)
    }

    @Test
    fun `a null name is carried across as null rather than defaulted`() {
        val apiSource = ApiSource(id = "bbc-news", name = null)

        val entity = apiSource.toSourceEntity()

        assertEquals("bbc-news", entity.id)
        assertNull(entity.name)
    }

    @Test
    fun `a source with nothing set maps to an entity with nothing set`() {
        val entity = ApiSource().toSourceEntity()

        assertEquals(Source(null, null), entity)
    }

    @Test
    fun `empty strings are preserved and not turned into nulls`() {
        val apiSource = ApiSource(id = "", name = "")

        assertEquals(Source("", ""), apiSource.toSourceEntity())
    }
}