// Generated by TestForge.
package com.joydipbhakat.newsapp.ui.language

import app.cash.turbine.test
import com.joydipbhakat.newsapp.data.network.models.ApiArticles
import com.joydipbhakat.newsapp.data.network.models.ApiSource
import com.joydipbhakat.newsapp.data.repository.TopHeadlineRepository
import com.joydipbhakat.newsapp.ui.UIState
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.mockito.kotlin.doReturn
import org.mockito.kotlin.mock
import org.mockito.kotlin.whenever

@OptIn(ExperimentalCoroutinesApi::class)
class LanguageViewModelTest {

    private val languageViewModelRepository: TopHeadlineRepository = mock()

    private val languageViewModelLanguages = listOf("en" to "English", "fr" to "French")

    private fun languageViewModelArticle(title: String) = ApiArticles(
        apiSource = ApiSource(id = "bbc-news", name = "BBC News"),
        title = title,
        description = "Description of $title",
        url = "https://example.com/$title",
        urlToImage = "https://example.com/$title.png"
    )

    // Both collections in this view model run through flowOn(Dispatchers.IO), a real
    // thread pool that no test dispatcher controls. Reading .value straight after the
    // call races that hop, so these wait for the state to leave Loading instead of
    // assuming how many emissions arrive or in what order.
    private suspend fun languageViewModelSettledState(
        viewModel: LanguageViewModel
    ): UIState<List<ApiArticles>> {
        var latest: UIState<List<ApiArticles>> = UIState.Loading
        viewModel.uiStateForLanguage.test {
            latest = awaitItem()
            while (latest is UIState.Loading) {
                latest = awaitItem()
            }
            cancelAndIgnoreRemainingEvents()
        }
        return latest
    }

    @Before
    fun setUp() {
        Dispatchers.setMain(UnconfinedTestDispatcher())
        whenever(languageViewModelRepository.getLanguages())
            .thenReturn(flowOf(languageViewModelLanguages))
    }

    // No @After resetting Main on purpose. Nothing clears these view models, so work
    // launched into viewModelScope can still be in flight when a test ends, and
    // anything that hopped through flowOn(Dispatchers.IO) resumes onto Main after
    // that. Pulling Main away from it does not fail one test — it takes down the
    // whole suite with a CoroutinesInternalError. Main is left installed; every test
    // class here installs its own in @Before.

    @Test
    fun `languages are loaded from the repository on construction`() = runTest {
        val viewModel = LanguageViewModel(languageViewModelRepository)

        viewModel.languages.test {
            var latest = awaitItem()
            while (latest.isEmpty()) {
                latest = awaitItem()
            }
            assertEquals(languageViewModelLanguages, latest)
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `the news state is Loading before any language is chosen`() {
        val viewModel = LanguageViewModel(languageViewModelRepository)

        assertEquals(UIState.Loading, viewModel.uiStateForLanguage.value)
    }

    @Test
    fun `news from both languages is concatenated, first language first`() = runTest {
        val english = languageViewModelArticle("English headline")
        val french = languageViewModelArticle("French headline")
        doReturn(flowOf(listOf(english))).whenever(languageViewModelRepository)
            .getLanguageNews("en")
        doReturn(flowOf(listOf(french))).whenever(languageViewModelRepository)
            .getLanguageNews("fr")
        val viewModel = LanguageViewModel(languageViewModelRepository)

        viewModel.getNewsBasedOnLanguage("en", "fr")

        assertEquals(
            UIState.Success(listOf(english, french)),
            languageViewModelSettledState(viewModel)
        )
    }

    @Test
    fun `two empty responses produce an empty success rather than an error`() = runTest {
        doReturn(flowOf(emptyList<ApiArticles>())).whenever(languageViewModelRepository)
            .getLanguageNews("en")
        doReturn(flowOf(emptyList<ApiArticles>())).whenever(languageViewModelRepository)
            .getLanguageNews("fr")
        val viewModel = LanguageViewModel(languageViewModelRepository)

        viewModel.getNewsBasedOnLanguage("en", "fr")

        assertEquals(
            UIState.Success(emptyList<ApiArticles>()),
            languageViewModelSettledState(viewModel)
        )
    }

    @Test
    fun `a failure in either language leaves the state in Error carrying the cause`() = runTest {
        doReturn(flowOf(listOf(languageViewModelArticle("English headline"))))
            .whenever(languageViewModelRepository)
            .getLanguageNews("en")
        doReturn(flow<List<ApiArticles>> { throw RuntimeException("no network") })
            .whenever(languageViewModelRepository)
            .getLanguageNews("fr")
        val viewModel = LanguageViewModel(languageViewModelRepository)

        viewModel.getNewsBasedOnLanguage("en", "fr")

        val state = languageViewModelSettledState(viewModel)
        assertTrue("expected an Error state but was $state", state is UIState.Error)
        assertTrue(
            "the message should carry the cause but was ${(state as UIState.Error).message}",
            state.message.contains("no network")
        )
    }
}