// Generated by TestForge.
package com.joydipbhakat.newsapp.data.pagination

import androidx.paging.ExperimentalPagingApi
import androidx.paging.LoadType
import androidx.paging.PagingConfig
import androidx.paging.PagingSource
import androidx.paging.PagingState
import androidx.paging.RemoteMediator
import com.joydipbhakat.newsapp.data.local.DatabaseService
import com.joydipbhakat.newsapp.data.local.entity.Article
import com.joydipbhakat.newsapp.data.local.entity.RemoteKeys
import com.joydipbhakat.newsapp.data.local.entity.Source
import com.joydipbhakat.newsapp.data.network.api.NetworkService
import com.joydipbhakat.newsapp.data.network.models.ApiArticles
import com.joydipbhakat.newsapp.data.network.models.ApiSource
import com.joydipbhakat.newsapp.data.network.models.NewsSourcesResponse
import com.joydipbhakat.newsapp.data.network.models.TopHeadlineResponse
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

@OptIn(ExperimentalPagingApi::class)
class TopHeadlineRemoteMediatorTest {

    private val topHeadlineRemoteMediatorNetwork = TopHeadlineRemoteMediatorFakeNetworkService()
    private val topHeadlineRemoteMediatorDatabase = TopHeadlineRemoteMediatorFakeDatabaseService()

    private val topHeadlineRemoteMediatorSubject = TopHeadlineRemoteMediator(
        networkService = topHeadlineRemoteMediatorNetwork,
        databaseService = topHeadlineRemoteMediatorDatabase
    )

    private fun topHeadlineRemoteMediatorApiArticle(url: String) = ApiArticles(
        apiSource = ApiSource(id = "bbc-news", name = "BBC News"),
        title = "Headline",
        description = "Description",
        url = url,
        urlToImage = "https://example.com/image.png"
    )

    private fun topHeadlineRemoteMediatorEntity(url: String) = Article(
        title = "Headline",
        description = "Description",
        url = url,
        urlToImage = "https://example.com/image.png",
        source = Source("bbc-news", "BBC News")
    )

    private fun topHeadlineRemoteMediatorState(
        articles: List<Article> = emptyList(),
        anchorPosition: Int? = null
    ): PagingState<Int, Article> {
        val pages: List<PagingSource.LoadResult.Page<Int, Article>> =
            if (articles.isEmpty()) {
                emptyList()
            } else {
                listOf(
                    PagingSource.LoadResult.Page<Int, Article>(
                        data = articles,
                        prevKey = null,
                        nextKey = null
                    )
                )
            }
        return PagingState(
            pages = pages,
            anchorPosition = anchorPosition,
            config = PagingConfig(pageSize = 1, enablePlaceholders = false),
            leadingPlaceholderCount = 0
        )
    }

    @Test
    fun `a refresh with no stored keys asks for the first page`() = runTest {
        topHeadlineRemoteMediatorNetwork.paginationResponse = TopHeadlineResponse(
            articles = listOf(topHeadlineRemoteMediatorApiArticle("https://example.com/one"))
        )

        val result = topHeadlineRemoteMediatorSubject.load(
            LoadType.REFRESH,
            topHeadlineRemoteMediatorState()
        )

        assertEquals(listOf(1), topHeadlineRemoteMediatorNetwork.requestedPages)
        assertTrue("expected Success but was $result", result is RemoteMediator.MediatorResult.Success)
        assertFalse((result as RemoteMediator.MediatorResult.Success).endOfPaginationReached)
    }

    @Test
    fun `a refresh clears the existing articles and keys before inserting`() = runTest {
        topHeadlineRemoteMediatorNetwork.paginationResponse = TopHeadlineResponse(
            articles = listOf(topHeadlineRemoteMediatorApiArticle("https://example.com/one"))
        )

        topHeadlineRemoteMediatorSubject.load(
            LoadType.REFRESH,
            topHeadlineRemoteMediatorState()
        )

        assertEquals(1, topHeadlineRemoteMediatorDatabase.articlesCleared)
        assertEquals(1, topHeadlineRemoteMediatorDatabase.remoteKeysCleared)
        assertEquals(
            listOf(topHeadlineRemoteMediatorEntity("https://example.com/one")),
            topHeadlineRemoteMediatorDatabase.insertedArticles
        )
    }

    @Test
    fun `the first page stores no previous key and a next key`() = runTest {
        topHeadlineRemoteMediatorNetwork.paginationResponse = TopHeadlineResponse(
            articles = listOf(topHeadlineRemoteMediatorApiArticle("https://example.com/one"))
        )

        topHeadlineRemoteMediatorSubject.load(
            LoadType.REFRESH,
            topHeadlineRemoteMediatorState()
        )

        assertEquals(
            listOf(
                RemoteKeys(
                    articleUrl = "https://example.com/one",
                    prevKey = null,
                    nextKey = 2
                )
            ),
            topHeadlineRemoteMediatorDatabase.insertedRemoteKeys
        )
    }

    @Test
    fun `an empty response ends pagination and stores no next key`() = runTest {
        topHeadlineRemoteMediatorNetwork.paginationResponse = TopHeadlineResponse(articles = emptyList())

        val result = topHeadlineRemoteMediatorSubject.load(
            LoadType.REFRESH,
            topHeadlineRemoteMediatorState()
        )

        assertTrue("expected Success but was $result", result is RemoteMediator.MediatorResult.Success)
        assertTrue((result as RemoteMediator.MediatorResult.Success).endOfPaginationReached)
        assertTrue(topHeadlineRemoteMediatorDatabase.insertedRemoteKeys.isEmpty())
    }

    @Test
    fun `a prepend with no previous key ends pagination without calling the network`() = runTest {
        val article = topHeadlineRemoteMediatorEntity("https://example.com/one")
        topHeadlineRemoteMediatorDatabase.remoteKeysByUrl[article.url] =
            RemoteKeys(articleUrl = article.url, prevKey = null, nextKey = 2)

        val result = topHeadlineRemoteMediatorSubject.load(
            LoadType.PREPEND,
            topHeadlineRemoteMediatorState(articles = listOf(article))
        )

        assertTrue("expected Success but was $result", result is RemoteMediator.MediatorResult.Success)
        assertTrue((result as RemoteMediator.MediatorResult.Success).endOfPaginationReached)
        assertTrue(topHeadlineRemoteMediatorNetwork.requestedPages.isEmpty())
    }

    @Test
    fun `an append with no next key ends pagination without calling the network`() = runTest {
        val article = topHeadlineRemoteMediatorEntity("https://example.com/one")
        topHeadlineRemoteMediatorDatabase.remoteKeysByUrl[article.url] =
            RemoteKeys(articleUrl = article.url, prevKey = 1, nextKey = null)

        val result = topHeadlineRemoteMediatorSubject.load(
            LoadType.APPEND,
            topHeadlineRemoteMediatorState(articles = listOf(article))
        )

        assertTrue("expected Success but was $result", result is RemoteMediator.MediatorResult.Success)
        assertTrue((result as RemoteMediator.MediatorResult.Success).endOfPaginationReached)
        assertTrue(topHeadlineRemoteMediatorNetwork.requestedPages.isEmpty())
    }

    @Test
    fun `an append follows the stored next key and does not clear the table`() = runTest {
        val article = topHeadlineRemoteMediatorEntity("https://example.com/one")
        topHeadlineRemoteMediatorDatabase.remoteKeysByUrl[article.url] =
            RemoteKeys(articleUrl = article.url, prevKey = null, nextKey = 3)
        topHeadlineRemoteMediatorNetwork.paginationResponse = TopHeadlineResponse(
            articles = listOf(topHeadlineRemoteMediatorApiArticle("https://example.com/two"))
        )

        topHeadlineRemoteMediatorSubject.load(
            LoadType.APPEND,
            topHeadlineRemoteMediatorState(articles = listOf(article))
        )

        assertEquals(listOf(3), topHeadlineRemoteMediatorNetwork.requestedPages)
        assertEquals(0, topHeadlineRemoteMediatorDatabase.articlesCleared)
        assertEquals(
            listOf(
                RemoteKeys(
                    articleUrl = "https://example.com/two",
                    prevKey = 2,
                    nextKey = 4
                )
            ),
            topHeadlineRemoteMediatorDatabase.insertedRemoteKeys
        )
    }

    @Test
    fun `a network failure is reported as an error rather than thrown`() = runTest {
        topHeadlineRemoteMediatorNetwork.failure = RuntimeException("no network")

        val result = topHeadlineRemoteMediatorSubject.load(
            LoadType.REFRESH,
            topHeadlineRemoteMediatorState()
        )

        assertTrue("expected Error but was $result", result is RemoteMediator.MediatorResult.Error)
        assertEquals(
            "no network",
            (result as RemoteMediator.MediatorResult.Error).throwable.message
        )
    }
}

private class TopHeadlineRemoteMediatorFakeNetworkService : NetworkService {
    var paginationResponse = TopHeadlineResponse()
    var failure: Exception? = null
    val requestedPages = mutableListOf<Int>()

    override suspend fun getTopHeadlinePagination(page: Int): TopHeadlineResponse {
        failure?.let { throw it }
        requestedPages += page
        return paginationResponse
    }

    override suspend fun getTopHeadline(country: String) = TopHeadlineResponse()

    override suspend fun getNewsSources() = NewsSourcesResponse()

    override suspend fun getLanguage(language: String) = TopHeadlineResponse()

    override suspend fun getNewsSearch(q: String) = TopHeadlineResponse()
}

private class TopHeadlineRemoteMediatorFakeDatabaseService : DatabaseService {
    var articlesCleared = 0
    var remoteKeysCleared = 0
    val insertedArticles = mutableListOf<Article>()
    val insertedRemoteKeys = mutableListOf<RemoteKeys>()
    val remoteKeysByUrl = mutableMapOf<String, RemoteKeys>()

    override suspend fun clearArticles() {
        articlesCleared++
    }

    override suspend fun insertArticles(articles: List<Article>) {
        insertedArticles += articles
    }

    override suspend fun clearRemoteKeys() {
        remoteKeysCleared++
    }

    override suspend fun insertRemoteKeys(remoteKeys: List<RemoteKeys>) {
        insertedRemoteKeys += remoteKeys
    }

    override suspend fun getRemoteKey(articleId: String): RemoteKeys? = remoteKeysByUrl[articleId]

    override fun pagingSource(): PagingSource<Int, Article> =
        object : PagingSource<Int, Article>() {
            override fun getRefreshKey(state: PagingState<Int, Article>): Int? = null

            override suspend fun load(params: LoadParams<Int>): LoadResult<Int, Article> =
                LoadResult.Page(data = emptyList(), prevKey = null, nextKey = null)
        }

    override suspend fun withTransaction(block: suspend () -> Unit) {
        block()
    }

    override fun getArticles(): Flow<List<Article>> = flowOf(insertedArticles.toList())

    override fun clearAndInsert(article: List<Article>) {
        insertedArticles.clear()
        insertedArticles += article
    }
}