// Generated by TestForge.
package com.joydipbhakat.newsapp.ui.offlinearticles

import com.joydipbhakat.newsapp.data.local.entity.Article
import com.joydipbhakat.newsapp.data.local.entity.Source
import com.joydipbhakat.newsapp.data.repository.TopHeadlineRepository
import com.joydipbhakat.newsapp.ui.UIState
import com.joydipbhakat.newsapp.utils.NetworkHelper
import com.joydipbhakat.newsapp.utils.TestDispatcherProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.mockito.kotlin.mock
import org.mockito.kotlin.never
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever

@OptIn(ExperimentalCoroutinesApi::class)
class OfflineArticlesViewModelTest {

    private val offlineArticlesRepository: TopHeadlineRepository = mock()
    private val offlineArticlesDispatchers = TestDispatcherProvider()

    private val offlineArticlesEntity = Article(
        title = "Headline",
        description = "Description",
        url = "https://example.com/article",
        urlToImage = "https://example.com/image.png",
        source = Source("bbc-news", "BBC News")
    )

    // NetworkHelper is an interface, so the online/offline branch is chosen by a real
    // implementation rather than by a stub.
    private class OfflineArticlesFakeNetworkHelper(private val online: Boolean) : NetworkHelper {
        override fun isOnline(): Boolean = online
    }

    @Before
    fun setUp() {
        Dispatchers.setMain(UnconfinedTestDispatcher())
    }

    // No @After resetting Main on purpose. Nothing clears these view models, so work
    // launched into viewModelScope can still be in flight when a test ends, and
    // anything that hopped through flowOn(Dispatchers.IO) resumes onto Main after
    // that. Pulling Main away from it does not fail one test — it takes down the
    // whole suite with a CoroutinesInternalError. Main is left installed; every test
    // class here installs its own in @Before.

    private fun offlineArticlesViewModel(online: Boolean) = OfflineArticlesViewModel(
        offlineArticlesRepository,
        offlineArticlesDispatchers,
        OfflineArticlesFakeNetworkHelper(online)
    )

    @Test
    fun `when online the articles are fetched through the network path`() = runTest {
        whenever(offlineArticlesRepository.getArticles("us"))
            .thenReturn(flowOf(listOf(offlineArticlesEntity)))

        val viewModel = offlineArticlesViewModel(online = true)

        verify(offlineArticlesRepository).getArticles("us")
        verify(offlineArticlesRepository, never()).getArticlesDirectlyFromDB()
        assertEquals(UIState.Success(listOf(offlineArticlesEntity)), viewModel.uiState.value)
    }

    @Test
    fun `when offline the articles come straight from the database`() = runTest {
        whenever(offlineArticlesRepository.getArticlesDirectlyFromDB())
            .thenReturn(flowOf(listOf(offlineArticlesEntity)))

        val viewModel = offlineArticlesViewModel(online = false)

        verify(offlineArticlesRepository).getArticlesDirectlyFromDB()
        verify(offlineArticlesRepository, never()).getArticles("us")
        assertEquals(UIState.Success(listOf(offlineArticlesEntity)), viewModel.uiState.value)
    }

    @Test
    fun `an empty database is a success carrying no articles`() = runTest {
        whenever(offlineArticlesRepository.getArticlesDirectlyFromDB())
            .thenReturn(flowOf(emptyList()))

        val viewModel = offlineArticlesViewModel(online = false)

        assertEquals(UIState.Success(emptyList<Article>()), viewModel.uiState.value)
    }

    @Test
    fun `a failure on the network path leaves the state in Error`() = runTest {
        whenever(offlineArticlesRepository.getArticles("us"))
            .thenReturn(flow { throw RuntimeException("no network") })

        val viewModel = offlineArticlesViewModel(online = true)

        assertEquals(
            UIState.Error("Error occurred due to some reason"),
            viewModel.uiState.value
        )
    }

    @Test
    fun `a failure on the database path leaves the state in Error`() = runTest {
        whenever(offlineArticlesRepository.getArticlesDirectlyFromDB())
            .thenReturn(flow { throw RuntimeException("database is gone") })

        val viewModel = offlineArticlesViewModel(online = false)

        assertEquals(
            UIState.Error("Error occurred due to some reason"),
            viewModel.uiState.value
        )
    }
}