// Generated by TestForge.
package com.joydipbhakat.newsapp.data.repository

import android.content.Context
import com.google.gson.Gson
import com.joydipbhakat.newsapp.data.local.DatabaseService
import com.joydipbhakat.newsapp.data.local.entity.Article
import com.joydipbhakat.newsapp.data.local.entity.Source
import com.joydipbhakat.newsapp.data.network.api.NetworkService
import com.joydipbhakat.newsapp.data.network.models.ApiArticles
import com.joydipbhakat.newsapp.data.network.models.ApiSource
import com.joydipbhakat.newsapp.data.network.models.NewsSources
import com.joydipbhakat.newsapp.data.network.models.NewsSourcesResponse
import com.joydipbhakat.newsapp.data.network.models.TopHeadlineResponse
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.mockito.kotlin.doReturn
import org.mockito.kotlin.doThrow
import org.mockito.kotlin.mock
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever

class TopHeadlineRepositoryFlowsTest {

    private val topHeadlineRepositoryNetworkService: NetworkService = mock()
    private val topHeadlineRepositoryDatabaseService: DatabaseService = mock()
    private val topHeadlineRepositoryContext: Context = mock()

    private lateinit var topHeadlineRepositorySubject: TopHeadlineRepository

    private val topHeadlineRepositoryApiArticle = ApiArticles(
        apiSource = ApiSource(id = "bbc-news", name = "BBC News"),
        title = "Headline",
        description = "Description",
        url = "https://example.com/article",
        urlToImage = "https://example.com/image.png"
    )

    private val topHeadlineRepositoryEntity = Article(
        title = "Headline",
        description = "Description",
        url = "https://example.com/article",
        urlToImage = "https://example.com/image.png",
        source = Source("bbc-news", "BBC News")
    )

    @Before
    fun setUp() {
        topHeadlineRepositorySubject = TopHeadlineRepository(
            topHeadlineRepositoryNetworkService,
            topHeadlineRepositoryDatabaseService,
            topHeadlineRepositoryContext,
            Gson()
        )
    }

    @Test
    fun `getNewsSources unwraps the sources from the response`() = runTest {
        val sources = listOf(NewsSources(id = "bbc-news", name = "BBC News"))
        doReturn(NewsSourcesResponse(status = "ok", sources = sources))
            .whenever(topHeadlineRepositoryNetworkService)
            .getNewsSources()

        assertEquals(sources, topHeadlineRepositorySubject.getNewsSources().first())
    }

    @Test
    fun `getNewsSources emits an empty list when the response carries none`() = runTest {
        doReturn(NewsSourcesResponse(status = "ok"))
            .whenever(topHeadlineRepositoryNetworkService)
            .getNewsSources()

        assertEquals(
            emptyList<NewsSources>(),
            topHeadlineRepositorySubject.getNewsSources().first()
        )
    }

    @Test
    fun `getLanguageNews asks the service for that language and unwraps the articles`() = runTest {
        doReturn(TopHeadlineResponse(articles = listOf(topHeadlineRepositoryApiArticle)))
            .whenever(topHeadlineRepositoryNetworkService)
            .getLanguage("fr")

        val result = topHeadlineRepositorySubject.getLanguageNews("fr").first()

        assertEquals(listOf(topHeadlineRepositoryApiArticle), result)
        verify(topHeadlineRepositoryNetworkService).getLanguage("fr")
    }

    @Test
    fun `getNewsSearch passes the query through and unwraps the articles`() = runTest {
        doReturn(TopHeadlineResponse(articles = listOf(topHeadlineRepositoryApiArticle)))
            .whenever(topHeadlineRepositoryNetworkService)
            .getNewsSearch("kotlin")

        val result = topHeadlineRepositorySubject.getNewsSearch("kotlin").first()

        assertEquals(listOf(topHeadlineRepositoryApiArticle), result)
        verify(topHeadlineRepositoryNetworkService).getNewsSearch("kotlin")
    }

    @Test
    fun `getArticlesDirectlyFromDB hands back the database flow without touching the network`() =
        runTest {
            whenever(topHeadlineRepositoryDatabaseService.getArticles())
                .thenReturn(flowOf(listOf(topHeadlineRepositoryEntity)))

            val result = topHeadlineRepositorySubject.getArticlesDirectlyFromDB().first()

            assertEquals(listOf(topHeadlineRepositoryEntity), result)
        }

    @Test
    fun `getArticles stores the mapped entities and then emits what the database holds`() =
        runTest {
            doReturn(TopHeadlineResponse(articles = listOf(topHeadlineRepositoryApiArticle)))
                .whenever(topHeadlineRepositoryNetworkService)
                .getTopHeadline("us")
            whenever(topHeadlineRepositoryDatabaseService.getArticles())
                .thenReturn(flowOf(listOf(topHeadlineRepositoryEntity)))

            val result = topHeadlineRepositorySubject.getArticles("us").first()

            verify(topHeadlineRepositoryDatabaseService)
                .clearAndInsert(listOf(topHeadlineRepositoryEntity))
            assertEquals(listOf(topHeadlineRepositoryEntity), result)
        }

    @Test
    fun `getArticles swallows a network failure and emits nothing at all`() = runTest {
        doThrow(RuntimeException("no network"))
            .whenever(topHeadlineRepositoryNetworkService)
            .getTopHeadline("us")

        val emissions = topHeadlineRepositorySubject.getArticles("us").toList()

        assertTrue("expected no emissions but got $emissions", emissions.isEmpty())
    }
}