// Generated by TestForge.
package com.joydipbhakat.newsapp.utils

import android.content.Context
import android.net.ConnectivityManager
import android.net.Network
import android.net.NetworkCapabilities
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.mockito.kotlin.mock
import org.mockito.kotlin.whenever

class DefaultNetworkHelperTest {

    private val defaultNetworkHelperContext: Context = mock()
    private val defaultNetworkHelperConnectivityManager: ConnectivityManager = mock()
    private val defaultNetworkHelperNetwork: Network = mock()
    private val defaultNetworkHelperCapabilities: NetworkCapabilities = mock()

    private lateinit var defaultNetworkHelperSubject: DefaultNetworkHelper

    @Before
    fun setUp() {
        whenever(defaultNetworkHelperContext.getSystemService(Context.CONNECTIVITY_SERVICE))
            .thenReturn(defaultNetworkHelperConnectivityManager)
        defaultNetworkHelperSubject = DefaultNetworkHelper(defaultNetworkHelperContext)
    }

    private fun defaultNetworkHelperGiveCapabilities(internet: Boolean, validated: Boolean) {
        whenever(defaultNetworkHelperConnectivityManager.activeNetwork)
            .thenReturn(defaultNetworkHelperNetwork)
        whenever(
            defaultNetworkHelperConnectivityManager
                .getNetworkCapabilities(defaultNetworkHelperNetwork)
        ).thenReturn(defaultNetworkHelperCapabilities)
        whenever(
            defaultNetworkHelperCapabilities
                .hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
        ).thenReturn(internet)
        whenever(
            defaultNetworkHelperCapabilities
                .hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)
        ).thenReturn(validated)
    }

    @Test
    fun `online when the active network both reaches the internet and is validated`() {
        defaultNetworkHelperGiveCapabilities(internet = true, validated = true)

        assertTrue(defaultNetworkHelperSubject.isOnline())
    }

    @Test
    fun `offline when there is no active network at all`() {
        whenever(defaultNetworkHelperConnectivityManager.activeNetwork).thenReturn(null)

        assertFalse(defaultNetworkHelperSubject.isOnline())
    }

    @Test
    fun `offline when the active network reports no capabilities`() {
        whenever(defaultNetworkHelperConnectivityManager.activeNetwork)
            .thenReturn(defaultNetworkHelperNetwork)
        whenever(
            defaultNetworkHelperConnectivityManager
                .getNetworkCapabilities(defaultNetworkHelperNetwork)
        ).thenReturn(null)

        assertFalse(defaultNetworkHelperSubject.isOnline())
    }

    @Test
    fun `offline when the network cannot reach the internet`() {
        defaultNetworkHelperGiveCapabilities(internet = false, validated = true)

        assertFalse(defaultNetworkHelperSubject.isOnline())
    }

    @Test
    fun `offline when the network reaches the internet but has not been validated`() {
        defaultNetworkHelperGiveCapabilities(internet = true, validated = false)

        assertFalse(defaultNetworkHelperSubject.isOnline())
    }
}