// Generated by TestForge.
package com.joydipbhakat.newsapp.ui.topheadline

import com.joydipbhakat.newsapp.data.network.models.ApiArticles
import com.joydipbhakat.newsapp.data.network.models.ApiSource
import com.joydipbhakat.newsapp.data.repository.TopHeadlineRepository
import com.joydipbhakat.newsapp.ui.UIState
import com.joydipbhakat.newsapp.utils.AppUtils
import com.joydipbhakat.newsapp.utils.TestDispatcherProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.mockito.kotlin.doReturn
import org.mockito.kotlin.mock
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever

@OptIn(ExperimentalCoroutinesApi::class)
class TopHeadlineViewModelTest {

    private val topHeadlineViewModelRepository: TopHeadlineRepository = mock()
    private val topHeadlineViewModelDispatchers = TestDispatcherProvider()

    private val topHeadlineViewModelArticle = ApiArticles(
        apiSource = ApiSource(id = "bbc-news", name = "BBC News"),
        title = "Headline",
        description = "Description",
        url = "https://example.com/article",
        urlToImage = "https://example.com/image.png"
    )

    @Before
    fun setUp() {
        Dispatchers.setMain(UnconfinedTestDispatcher())
    }

    // No @After resetting Main on purpose. Nothing clears these view models, so work
    // launched into viewModelScope can still be in flight when a test ends, and
    // anything that hopped through flowOn(Dispatchers.IO) resumes onto Main after
    // that. Pulling Main away from it does not fail one test — it takes down the
    // whole suite with a CoroutinesInternalError. Main is left installed; every test
    // class here installs its own in @Before.

    @Test
    fun `news is fetched for the default country as soon as the view model exists`() = runTest {
        doReturn(flowOf(listOf(topHeadlineViewModelArticle)))
            .whenever(topHeadlineViewModelRepository)
            .getTopHeadline(AppUtils.COUNTRY)

        val viewModel = TopHeadlineViewModel(
            topHeadlineViewModelRepository,
            topHeadlineViewModelDispatchers
        )

        verify(topHeadlineViewModelRepository).getTopHeadline(AppUtils.COUNTRY)
        assertEquals(
            UIState.Success(listOf(topHeadlineViewModelArticle)),
            viewModel.uiState.value
        )
    }

    @Test
    fun `an empty response is a success carrying no articles`() = runTest {
        doReturn(flowOf(emptyList<ApiArticles>()))
            .whenever(topHeadlineViewModelRepository)
            .getTopHeadline(AppUtils.COUNTRY)

        val viewModel = TopHeadlineViewModel(
            topHeadlineViewModelRepository,
            topHeadlineViewModelDispatchers
        )

        assertEquals(UIState.Success(emptyList<ApiArticles>()), viewModel.uiState.value)
    }

    @Test
    fun `a failing repository leaves the state in Error`() = runTest {
        doReturn(flow<List<ApiArticles>> { throw RuntimeException("no network") })
            .whenever(topHeadlineViewModelRepository)
            .getTopHeadline(AppUtils.COUNTRY)

        val viewModel = TopHeadlineViewModel(
            topHeadlineViewModelRepository,
            topHeadlineViewModelDispatchers
        )

        assertEquals(
            UIState.Error("Error occurred due to some reason"),
            viewModel.uiState.value
        )
    }

    @Test
    fun `fetchNews called again after a failure recovers to Success`() = runTest {
        doReturn(flow<List<ApiArticles>> { throw RuntimeException("no network") })
            .whenever(topHeadlineViewModelRepository)
            .getTopHeadline(AppUtils.COUNTRY)
        val viewModel = TopHeadlineViewModel(
            topHeadlineViewModelRepository,
            topHeadlineViewModelDispatchers
        )
        assertEquals(UIState.Error("Error occurred due to some reason"), viewModel.uiState.value)

        doReturn(flowOf(listOf(topHeadlineViewModelArticle)))
            .whenever(topHeadlineViewModelRepository)
            .getTopHeadline(AppUtils.COUNTRY)
        viewModel.fetchNews()

        assertEquals(
            UIState.Success(listOf(topHeadlineViewModelArticle)),
            viewModel.uiState.value
        )
    }
}