// Generated by TestForge.
package com.joydipbhakat.newsapp.ui.topheadlinepagination

import androidx.paging.PagingData
import app.cash.turbine.test
import com.joydipbhakat.newsapp.data.local.entity.Article
import com.joydipbhakat.newsapp.data.repository.TopHeadlineRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.Before
import org.junit.Test
import org.mockito.kotlin.mock
import org.mockito.kotlin.times
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever

@OptIn(ExperimentalCoroutinesApi::class)
class TopHeadlinePaginationViewModelTest {

    private val topHeadlinePaginationRepository: TopHeadlineRepository = mock()

    @Before
    fun setUp() {
        // cachedIn attaches to viewModelScope, whose context is Main.immediate.
        Dispatchers.setMain(UnconfinedTestDispatcher())
    }

    // No @After resetting Main on purpose. Nothing clears these view models, so work
    // launched into viewModelScope can still be in flight when a test ends, and
    // anything that hopped through flowOn(Dispatchers.IO) resumes onto Main after
    // that. Pulling Main away from it does not fail one test — it takes down the
    // whole suite with a CoroutinesInternalError. Main is left installed; every test
    // class here installs its own in @Before.

    @Test
    fun `the paging flow is taken from the repository`() = runTest {
        whenever(topHeadlinePaginationRepository.getArticlesFromPagination())
            .thenReturn(flowOf(PagingData.empty<Article>()))
        val viewModel = TopHeadlinePaginationViewModel(topHeadlinePaginationRepository)

        viewModel.getArticlesFromPagination().test {
            awaitItem()
            cancelAndIgnoreRemainingEvents()
        }

        verify(topHeadlinePaginationRepository).getArticlesFromPagination()
    }

    @Test
    fun `each call asks the repository again rather than reusing one flow`() = runTest {
        whenever(topHeadlinePaginationRepository.getArticlesFromPagination())
            .thenReturn(flowOf(PagingData.empty<Article>()))
        val viewModel = TopHeadlinePaginationViewModel(topHeadlinePaginationRepository)

        viewModel.getArticlesFromPagination()
        viewModel.getArticlesFromPagination()

        verify(topHeadlinePaginationRepository, times(2)).getArticlesFromPagination()
    }

    @Test
    fun `the repository is not touched until the flow is asked for`() {
        TopHeadlinePaginationViewModel(topHeadlinePaginationRepository)

        verify(topHeadlinePaginationRepository, times(0)).getArticlesFromPagination()
    }
}