// Generated by TestForge.
package com.joydipbhakat.newsapp.ui.countries

import app.cash.turbine.test
import com.joydipbhakat.newsapp.data.network.models.ApiArticles
import com.joydipbhakat.newsapp.data.network.models.ApiSource
import com.joydipbhakat.newsapp.data.network.models.Countries
import com.joydipbhakat.newsapp.data.repository.TopHeadlineRepository
import com.joydipbhakat.newsapp.ui.UIState
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Before
import org.junit.Test
import org.mockito.kotlin.doReturn
import org.mockito.kotlin.mock
import org.mockito.kotlin.whenever

@OptIn(ExperimentalCoroutinesApi::class)
class CountriesViewModelTest {

    private val countriesViewModelRepository: TopHeadlineRepository = mock()

    private val countriesViewModelArticle = ApiArticles(
        apiSource = ApiSource(id = "bbc-news", name = "BBC News"),
        title = "Headline",
        description = "Description",
        url = "https://example.com/article",
        urlToImage = "https://example.com/image.png"
    )

    private val countriesViewModelCountries = listOf(
        Countries(name = "United States", code = "us"),
        Countries(name = "India", code = "in")
    )

    @Before
    fun setUp() {
        // The view model launches on Dispatchers.Main and on viewModelScope's
        // Main.immediate, neither of which exists on the JVM until one is installed.
        Dispatchers.setMain(UnconfinedTestDispatcher())
        // loadCountries runs from the init block, so this has to be in place before
        // any instance is constructed.
        whenever(countriesViewModelRepository.getCountries())
            .thenReturn(flowOf(countriesViewModelCountries))
    }

    // No @After resetting Main on purpose. Nothing clears these view models, so work
    // launched into viewModelScope can still be in flight when a test ends, and
    // anything that hopped through flowOn(Dispatchers.IO) resumes onto Main after
    // that. Pulling Main away from it does not fail one test — it takes down the
    // whole suite with a CoroutinesInternalError. Main is left installed; every test
    // class here installs its own in @Before.

    @Test
    fun `countries are loaded from the repository on construction`() = runTest {
        val viewModel = CountriesViewModel(countriesViewModelRepository)

        // loadCountries collects through flowOn(Dispatchers.IO), which is a real
        // thread pool that no test dispatcher controls. Reading .value straight
        // after construction races that hop, so wait for the loaded value instead
        // of assuming how many emissions arrive or in what order.
        viewModel.countries.test {
            var latest = awaitItem()
            while (latest.isEmpty()) {
                latest = awaitItem()
            }
            assertEquals(countriesViewModelCountries, latest)
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `no country is selected and the headline state is Loading before any selection`() {
        val viewModel = CountriesViewModel(countriesViewModelRepository)

        assertNull(viewModel.selectedCountry.value)
        assertEquals(UIState.Loading, viewModel.uiStateForCountry.value)
    }

    @Test
    fun `onCountrySelected records the code and emits the headlines for it`() = runTest {
        doReturn(flowOf(listOf(countriesViewModelArticle)))
            .whenever(countriesViewModelRepository)
            .getTopHeadline("us")
        val viewModel = CountriesViewModel(countriesViewModelRepository)

        viewModel.onCountrySelected("us")

        assertEquals("us", viewModel.selectedCountry.value)
        assertEquals(
            UIState.Success(listOf(countriesViewModelArticle)),
            viewModel.uiStateForCountry.value
        )
    }

    @Test
    fun `an empty list from the repository is still a success`() = runTest {
        doReturn(flowOf(emptyList<ApiArticles>()))
            .whenever(countriesViewModelRepository)
            .getTopHeadline("in")
        val viewModel = CountriesViewModel(countriesViewModelRepository)

        viewModel.getTopHeadlinesBasedOnCountry("in")

        assertEquals(UIState.Success(emptyList<ApiArticles>()), viewModel.uiStateForCountry.value)
    }

    @Test
    fun `a failing repository leaves the headline state in Error`() = runTest {
        doReturn(flow<List<ApiArticles>> { throw RuntimeException("no network") })
            .whenever(countriesViewModelRepository)
            .getTopHeadline("us")
        val viewModel = CountriesViewModel(countriesViewModelRepository)

        viewModel.getTopHeadlinesBasedOnCountry("us")

        assertEquals(
            UIState.Error("Error occurred while obtaining required data"),
            viewModel.uiStateForCountry.value
        )
    }

    @Test
    fun `clearSelectedCountry drops the selection and returns the state to Loading`() = runTest {
        doReturn(flowOf(listOf(countriesViewModelArticle)))
            .whenever(countriesViewModelRepository)
            .getTopHeadline("us")
        val viewModel = CountriesViewModel(countriesViewModelRepository)
        viewModel.onCountrySelected("us")

        viewModel.clearSelectedCountry()

        assertNull(viewModel.selectedCountry.value)
        assertEquals(UIState.Loading, viewModel.uiStateForCountry.value)
    }
}