// Generated by TestForge.
package com.joydipbhakat.newsapp.data.network.api

import com.joydipbhakat.newsapp.utils.AppUtils
import okhttp3.Interceptor
import okhttp3.Protocol
import okhttp3.Request
import okhttp3.Response
import okhttp3.ResponseBody.Companion.toResponseBody
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test
import org.mockito.kotlin.any
import org.mockito.kotlin.mock
import org.mockito.kotlin.whenever

class ApiKeyInterceptorTest {

    private val apiKeyInterceptorSubject = ApiKeyInterceptor()

    /// Runs the interceptor over a request and hands back the one it actually sent on.
    private fun apiKeyInterceptorProceedWith(request: Request): Request {
        val chain: Interceptor.Chain = mock()
        whenever(chain.request()).thenReturn(request)
        var forwarded: Request? = null
        whenever(chain.proceed(any())).thenAnswer { invocation ->
            val sent = invocation.getArgument<Request>(0)
            forwarded = sent
            Response.Builder()
                .request(sent)
                .protocol(Protocol.HTTP_1_1)
                .code(200)
                .message("OK")
                .body("".toResponseBody(null))
                .build()
        }

        apiKeyInterceptorSubject.intercept(chain)

        return requireNotNull(forwarded) { "the interceptor never called proceed" }
    }

    private fun apiKeyInterceptorRequest(): Request =
        Request.Builder().url("https://newsapi.org/v2/top-headlines").build()

    @Test
    fun `the api key header is added to the outgoing request`() {
        val sent = apiKeyInterceptorProceedWith(apiKeyInterceptorRequest())

        assertEquals(AppUtils.API_KEY, sent.header("X-Api-Key"))
    }

    @Test
    fun `the user agent header is added to the outgoing request`() {
        val sent = apiKeyInterceptorProceedWith(apiKeyInterceptorRequest())

        assertEquals("ABC", sent.header("User-Agent"))
    }

    @Test
    fun `the original url and method are left alone`() {
        val original = apiKeyInterceptorRequest()

        val sent = apiKeyInterceptorProceedWith(original)

        assertEquals(original.url, sent.url)
        assertEquals("GET", sent.method)
    }

    @Test
    fun `an existing header on the request is carried through`() {
        val original = Request.Builder()
            .url("https://newsapi.org/v2/top-headlines")
            .header("Accept", "application/json")
            .build()

        val sent = apiKeyInterceptorProceedWith(original)

        assertEquals("application/json", sent.header("Accept"))
    }

    @Test
    fun `an api key already on the request is replaced rather than appended`() {
        val original = Request.Builder()
            .url("https://newsapi.org/v2/top-headlines")
            .header("X-Api-Key", "stale-key")
            .build()

        val sent = apiKeyInterceptorProceedWith(original)

        assertEquals(listOf(AppUtils.API_KEY), sent.headers.values("X-Api-Key"))
    }

    @Test
    fun `headers the interceptor does not set are absent`() {
        val sent = apiKeyInterceptorProceedWith(apiKeyInterceptorRequest())

        assertNull(sent.header("Authorization"))
    }
}